version: 2.1

jobs:
  build_deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Installing AWS CLI
          command: sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      - run: aws s3 sync ./app/build s3://learning-how-to-learn

workflows:
  execute_bulk:
    jobs:
      - build_deploy
