version: 2.1

jobs:
  build_deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: |
          # Install AWS CLI
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -q awscliv2.zip
          sudo ./aws/install --update
      - run: aws s3 sync ../web_project_1 s3://learning-how-to-learn

workflows:
  execute_bulk:
    jobs:
      - build_deploy
