version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0

jobs:
  build_deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: |
          # Install AWS CLI
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -q awscliv2.zip
          sudo ./aws/install --update
      - run: aws s3 sync . s3://learning-how-to-learn

    aws-cli-cred-setup:
      executor: aws-cli/default
      steps:
        - aws-cli/setup:
            aws-access-key-id: Access_key_ID
            aws-secret-access-key: Secret_access_key
            aws-region: Region

workflows:
  execute_bulk:
    jobs:
      - build_deploy
      - aws-cli-cred-setup:
          context: aws
